OpenLMIS/openlmis-referencedata-ui

- Jenkinsfile
- npm-shrinkwrap.json
- yarn.lock
Adding cleaning functions to Jenkinsfile, update older versions of files causing errors
> Update yarn, jenkinsfile, npm-shrinkwrap

- CHANGELOG.md
> OLMIS-7649: modified changelog

- CHANGELOG.md
- src/admin-data-import/Routing.jsx
- src/admin-data-import/_admin-data-import.scss
- src/admin-data-import/admin-data-import.html
- src/admin-data-import/admin-data-import.module.js
- src/admin-data-import/admin-data-import.routes.js
- src/admin-data-import/admin-data-import.service.js
- src/admin-data-import/admin-data-import.wrapper.jsx
- src/admin-data-import/components/AdminDataExportPage/AdminDataImportPage.jsx
- src/admin-data-import/components/AdminDataExportPage/index.jsx
- src/admin-data-import/consts.jsx
- src/admin-data-import/messages_en.json
Ticket: https://openlmis.atlassian.net/browse/OLMIS-7673
> OLMIS-7673: Add import page

- src/admin-data-import/admin-data-import.service.js
- src/admin-data-import/components/AdminDataExportPage/AdminDataImportPage.jsx
- src/admin-data-import/consts.jsx
Ticket: https://openlmis.atlassian.net/browse/OLMIS-7673
> OLMIS-7673: fixed toast message

- CHANGELOG.md
- src/referencedata-lot/lot.service.js
- src/referencedata-lot/lot.service.spec.js
- src/referencedata-orderable-fulfills/orderable-fulfills.run.js
- src/referencedata-orderable-fulfills/orderable-fulfills.service.js
- src/referencedata-orderable-fulfills/orderable-fulfills.service.spec.js
- src/referencedata-orderable/orderable.run.js
- src/referencedata-program/program.service.js
- src/referencedata-program/program.service.spec.js
- src/referencedata-user-programs-cache/program.service.decorator.spec.js
Ticket:
https://openlmis.atlassian.net/browse/OLMIS-7954
Changes:
Improved the scalability of local storage and login performance for /api/requisitionGroups request
> OLMIS-7954: Improved the scalability of local storage and login performance for /api/requisitionGroups request

- CHANGELOG.md
- src/openlmis-home-alerts-panel/_openlmis-home-alerts-panel.scss
- src/openlmis-home-alerts-panel/messages_en.json
- src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.component.js
- src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.controller.js
- src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.html
- src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.module.js
- src/openlmis-home-alerts-panel/openlmis-home-alerts-panel.service.js
- src/openlmis-home/_home.scss
- src/openlmis-home/home.html
Ticket:
https://openlmis.atlassian.net/browse/OLMIS-7976
Changes:
-added homepage alerts component
-component correction - it displayed on the entire page
> Olmis 7976: added homepage alerts component

- CHANGELOG.md
- src/admin-supply-line-list/facilities-popover.html
- src/admin-supply-line-list/messages_en.json
- src/admin-supply-line-list/supply-line-list.controller.js
- src/admin-supply-line-list/supply-line-list.controller.spec.js
- src/admin-supply-line-list/supply-line-list.html
Task:
https://openlmis.atlassian.net/browse/OLMIS-7749
Changes: 
Added note in popover on Supply Line page if there are no member facilities
> OLMIS-7749: Added note in popover on Supply Line page if there are no member facilities

- src/admin-user-roles/messages_en.json
- src/admin-user-roles/user-roles-tab.controller.js
- src/referencedata-role/role-assignment.js
ticket: https://openlmis.atlassian.net/browse/OIS-58
> OIS-58: Improve role Removal confirmation message

- src/admin-orderable-edit/messages_en.json
This change has been done as a part of internship program with Nikola
> OLMIS-6561: Fix typo in product add and edit view

- CHANGELOG.md
- src/select-products-modal/_select-products-modal.scss
- src/select-products-modal/select-products-modal.html
https://openlmis.atlassian.net/browse/OLMIS-6908
> OLMIS-6908: fix input onchange functionality

- CHANGELOG.md
- src/referencedata-requisition-group/requisition-group.service.js
- src/referencedata-requisition-group/requisition-group.service.spec.js
Task:
https://openlmis.atlassian.net/browse/OLMIS-7992
Changes:
Added requisition groups cache to enable Requisition view offline
> Olmis 7992

- src/admin-data-export/consts.jsx
- src/admin-data-import/consts.jsx
ticket: https://openlmis.atlassian.net/browse/OLMIS-7989?focusedCommentId=95360
> OLMIS-7989: modified import and export by adding one more type

- CHANGELOG.md
- src/openlmis-home-page-report/_home-page-report.scss
- src/openlmis-home-page-report/home-page-report.component.js
- src/openlmis-home-page-report/home-page-report.controller.js
- src/openlmis-home-page-report/home-page-report.html
- src/openlmis-home-page-report/home-page-report.module.js
- src/openlmis-home/home.html
Changes:
Created Home Page Report Component  and added it to home page
Task:
https://openlmis.atlassian.net/browse/SELV3-784
> SELV3-784: Added Home Page Report Component to home page

- src/admin-report-edit/admin-report-edit.controller.js
- src/admin-report-edit/admin-report-edit.routes.js
- src/report-category/report-category.service.js
- src/report-category/report-category.service.spec.js
- src/report/report-dashboard.service.js
- src/report/report-dashboard.service.spec.js
added fixes for report dashboard editing
> SELV3-782: added fixes for report dashboard editing

- src/admin-requisition-group-edit/requisition-group-edit.controller.js
resolving comment: https://openlmis.atlassian.net/browse/OLMIS-8056?focusedCommentId=96892
> OLMIS-8056: show current filter value

- src/admin-requisition-group-edit/_requisition-group-edit-form.scss
- src/admin-requisition-group-edit/member-facilities.html
Changes: 
* Filter button, and add facility button are now in one line
ticket: https://openlmis.atlassian.net/browse/OLMIS-8056
> OLMIS-8056: changed the alignement inside the toolbar

- src/admin-requisition-group-edit/_requisition-group-edit-form.scss
- src/admin-requisition-group-edit/member-facilities.html
Earlier for the purpose of this ticket toolbar above the table was styled. By mistake the styling affected not only the toolbar in the requisition group edit, but in whole app. This PR will fix this issue.
> OLMIS-8056: styled toolbar only for rg-edit form

- CHANGELOG.md
- src/referencedata-user/referencedata-user-resource.js
- src/referencedata-user/user-repository-impl.js
resolving ticket: https://openlmis.atlassian.net/browse/OLMIS-8095
> OLMIS-8095: improve user creation validation

- src/referencedata-user/user-repository-impl.js
- src/referencedata-user/user.js
resolving comment: https://openlmis.atlassian.net/browse/OLMIS-8095?focusedCommentId=97243
> OLMIS-8095: fixed problem with saving form twice with wrong data

- CHANGELOG.md
- src/admin-requisition-group-add/admin-requisition-group-add.routes.js
- src/admin-requisition-group-edit/requisition-group-edit.controller.js
- src/admin-requisition-group-list/requisition-group-list.controller.js
resolving ticket: https://openlmis.atlassian.net/browse/OLMIS-8107
> OLMIS-8107: Fixed breadcrumbs in add mode and removing facilities in edit mode
